CREATE TABLE `contact` (
  `CONTACT_ID` bigint(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`CONTACT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;

CREATE TABLE `personne` (
  `PERSONNE_ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `PRENOM` varchar(255) DEFAULT NULL,
  `NOM` varchar(255) DEFAULT NULL,
  `AGE` int(11) DEFAULT NULL,
  PRIMARY KEY (`PERSONNE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;

	ALTER TABLE user add email varchar(255) DEFAULT NULL;
	
	alter table user drop age;