CREATE TABLE `guide` (
  `GUIDE_ID` bigint(11) NOT NULL,
  `TITRE` varchar(255) DEFAULT NULL,
  `B_VISIBLE` tinyint(6) DEFAULT NULL,
  `DATE_PUBLICATION` date DEFAULT NULL,
  `DATE_MODIFICATION` date DEFAULT NULL,
  `IMAGE_COUVERTURE` blob,
  PRIMARY KEY (`GUIDE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
